#!/usr/bin/env perl

$latex         = 'platex %O -synctex=1 -interaction=nonstopmode %S';
$pdflatex      = 'pdflatex %O -synctex=1 -interaction=nonstopmode %S';
$lualatex      = 'lualatex %O -synctex=1 -interaction=nonstopmode %S';
$xelatex       = 'xelatex %O -synctex=1 -interaction=nonstopmode %S';
$biber         = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';
$bibtex        = 'pbibtex %O %B';
$makeindex     = 'makeindex %O -o %D %S';  # mendex/upmendex crashes for some unknown reason
$dvipdf        = 'dvipdfmx %O -o %D %S';
$dvips         = 'dvips %O -z -f %S | convbkmk -u > %D';
$ps2pdf        = 'ps2pdf %O %S %D';
$pdf_mode      = 5;
$pdf_previewer = 'mupdf';
$out_dir       = 'build';
