return {
    color_foreground        = "#d8dee9",
    color_background        = "#2e3440",
    color_cursor            = "#d8dee9",
    color_cursor_foreground = "#2e3440",
    color_highlight         = "#4c566a",
    color_bold              = "#d8dee9",

    color_0                 = "#3b4252",
    color_1                 = "#bf616a",
    color_2                 = "#a3be8c",
    color_3                 = "#ebcb8b",
    color_4                 = "#81a1c1",
    color_5                 = "#b48ead",
    color_6                 = "#88c0d0",
    color_7                 = "#e5e9f0",
    color_8                 = "#4c566a",
    color_9                 = "#bf616a",
    color_10                = "#a3be8c",
    color_11                = "#ebcb8b",
    color_12                = "#81a1c1",
    color_13                = "#b48ead",
    color_14                = "#8fbcbb",
    color_15                = "#eceff4",
}
